Install packer v1.6.6
packer-provisioner-serverspec doesn't work on packer 1.8+

```
$ packer build -debug build.pkr.hcl
Error: failed loading serverspec
  on build.pkr.hcl line 51:
  (source code not available)
The protocol of this plugin (protocol version 4 and lower) was deprecated,
please use a newer version of this plugin.Or use an older version of Packer (pre
1.7) with this plugin.
```